### ISSUE TITLE
入居者情報の文字コード

### ISSUE THREAD

**Issue by AllMightyGod** [mym-kingbob/garbage-plan#4]
１．入居者の情報メールがgmailにて自動的にフォワーディングされるときUTF-8 3 byteにインコディングされている事象。
２．入居者情報の文字が統一されていない事象（ある人は日本語、ある人は英語にて書いてる等）

**Comment by komayama** [comment]
2.に関しては，下に貼った日本語<->ローマ字の変換モジュールが使えそう
https://qiita.com/komorin0521/items/8cd1eb0cdb4a9ede217e
